name: SenpaiJepang
options:
  bundleIdPrefix: com.senpaijepang
targets:
  SenpaiJepang:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    infoPlist: Info.plist
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        GENERATE_INFOPLIST_FILE: NO
        DEVELOPMENT_TEAM: "" # Can be empty for local simulator builds
    dependencies:
      - package: netfox
    sources:
      - path: Sources/SenpaiJepangApp
  SenpaiJepangTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    sources:
      - path: Tests/SenpaiJepangAppTests
    dependencies:
      - target: SenpaiJepang

schemes:
  SenpaiJepang:
    build:
      targets:
        SenpaiJepang: all
    test:
      targets:
        - name: SenpaiJepangTests

packages:
  netfox:
    url: https://github.com/kasketis/netfox
    from: 1.21.0
